// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDyxMeb5zxPJsL-WROfmJG_UWys-fRlkrU',
    appId: '1:838476137369:web:f37c46c46b97d7246c0908',
    messagingSenderId: '838476137369',
    projectId: 'taiwanviewpoint-7b86e',
    authDomain: 'taiwanviewpoint-7b86e.firebaseapp.com',
    storageBucket: 'taiwanviewpoint-7b86e.appspot.com',
    measurementId: 'G-F2187QEB5W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYA8eZsAY1yyMhsRmkXN3tlXvMc_rWfTM',
    appId: '1:838476137369:android:5bed170e82a4efaf6c0908',
    messagingSenderId: '838476137369',
    projectId: 'taiwanviewpoint-7b86e',
    storageBucket: 'taiwanviewpoint-7b86e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-LX0tque-XdLAcoJwg201DTvDAPMLxew',
    appId: '1:838476137369:ios:c97bd172ca7daccb6c0908',
    messagingSenderId: '838476137369',
    projectId: 'taiwanviewpoint-7b86e',
    storageBucket: 'taiwanviewpoint-7b86e.appspot.com',
    iosClientId:
        '838476137369-7pb4h7nkc27lmui60e3t9msh0emhdqih.apps.googleusercontent.com',
    iosBundleId: 'meetstudio.taiwanviewpoint.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD-LX0tque-XdLAcoJwg201DTvDAPMLxew',
    appId: '1:838476137369:ios:d3c255dd0cd8b0746c0908',
    messagingSenderId: '838476137369',
    projectId: 'taiwanviewpoint-7b86e',
    storageBucket: 'taiwanviewpoint-7b86e.appspot.com',
    iosClientId:
        '838476137369-ndc1l6bte78cbhu4lgdt7t82a2u2jafm.apps.googleusercontent.com',
    iosBundleId: 'com.meetstudio.travel',
  );
}
